name: Testing
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: fwal/setup-swift@v1.3.0
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      env:
        KEY: ${{ secrets.KEY}} 
        SECRET: ${{ secrets.SECRET }}
      run: swift test -v
